"""initial_schema

Revision ID: 07f45e204cec
Revises: 
Create Date: 2026-09-28 23:17:53.542341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '07f45e204cec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('TOPUP', 'P2P_TRANSFER', 'PAYMENT_REQUEST_PAYMENT', name='transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='transaction_status'), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("alias ~ '^[a-z0-9_]{3,20}$'", name='chk_alias_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_alias'), 'users', ['alias'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('USER_WALLET', 'SYSTEM_OMNIBUS', name='account_type'), server_default=sa.text("'USER_WALLET'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('key', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='idempotency_status'), server_default=sa.text("'PROCESSING'"), nullable=False),
    sa.Column('response_code', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('debit_account_id', sa.UUID(), nullable=False),
    sa.Column('credit_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_positive_amount'),
    sa.CheckConstraint('debit_account_id <> credit_account_id', name='chk_different_accounts'),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_credit_acc', 'ledger_entries', ['credit_account_id'], unique=False)
    op.create_index('idx_ledger_debit_acc', 'ledger_entries', ['debit_account_id'], unique=False)
    op.create_index('idx_ledger_created_at', 'ledger_entries', [sa.text('created_at DESC')])
    op.create_table('payment_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('requester_account_id', sa.UUID(), nullable=False),
    sa.Column('payer_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REJECTED', 'CANCELLED', name='payment_request_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_pr_positive_amount'),
    sa.CheckConstraint('requester_account_id <> payer_account_id', name='chk_pr_different_accounts'),
    sa.ForeignKeyConstraint(['payer_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_requests_payer_status', 'payment_requests', ['payer_account_id', 'status'], unique=False)
    op.create_index('idx_payment_requests_requester_status', 'payment_requests', ['requester_account_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_requests_requester_status', table_name='payment_requests')
    op.drop_index('idx_payment_requests_payer_status', table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index('idx_ledger_debit_acc', table_name='ledger_entries')
    op.drop_index('idx_ledger_credit_acc', table_name='ledger_entries')
    op.drop_index('idx_ledger_created_at', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('audit_logs')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_alias'), table_name='users')
    op.drop_table('users')
    op.drop_table('transactions')
    for enum_name in ('payment_request_status', 'idempotency_status',
                      'account_type', 'user_role', 'transaction_status', 'transaction_type'):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
